# Generated by Django 4.2.10 on 2024-06-30 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('currency', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('plan_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AirPlanFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('feature_type', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_route', models.BooleanField(default=False)),
                ('needs_stripe', models.BooleanField(default=False)),
                ('razorpay_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stakeholder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay')], default='razorpay', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_link', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_link_id', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airpay.paymentgateway')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airpay.airplan')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airpay.airseller')),
            ],
        ),
        migrations.CreateModel(
            name='RazorpayRouteOnboardingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_user_id', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('legal_business_name', models.CharField(max_length=255)),
                ('customer_facing_business_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('business_type', models.CharField(blank=True, choices=[('individual', 'Individual'), ('llp', 'LLP'), ('private_limited', 'Private Limited'), ('public_limited', 'Public Limited'), ('partnership', 'Partnership'), ('proprietorship', 'Proprietorship'), ('trust', 'Trust'), ('society', 'Society'), ('not_yet_registered', 'Not Yet Registered'), ('educational_institutes', 'Educational Institutes'), ('ngo', 'NGO')], max_length=255, null=True)),
                ('business_category', models.CharField(blank=True, choices=[('financial_services', 'Financial Services'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('utilities', 'Utilities'), ('government', 'Government'), ('logistics', 'Logistics'), ('tours_and_travel', 'Tours and Travel'), ('transport', 'Transport'), ('ecommerce', 'Ecommerce'), ('food', 'Food'), ('it_and_software', 'IT and Software'), ('gaming', 'Gaming'), ('media_and_entertainment', 'Media and Entertainment'), ('services', 'Services'), ('housing', 'Housing'), ('not_for_profit', 'Not For Profit'), ('social', 'Social'), ('others', 'Others')], max_length=255, null=True)),
                ('sub_business_category', models.CharField(blank=True, choices=[('mutual_fund', 'mutual_fund'), ('lending', 'lending'), ('cryptocurrency', 'cryptocurrency'), ('insurance', 'insurance'), ('nbfc', 'nbfc'), ('cooperatives', 'cooperatives'), ('pension_fund', 'pension_fund'), ('forex', 'forex'), ('securities', 'securities'), ('commodities', 'commodities'), ('accounting', 'accounting'), ('financial_advisor', 'financial_advisor'), ('crowdfunding', 'crowdfunding'), ('trading', 'trading'), ('betting', 'betting'), ('get_rich_schemes', 'get_rich_schemes'), ('moneysend_funding', 'moneysend_funding'), ('wire_transfers_and_money_orders', 'wire_transfers_and_money_orders'), ('tax_preparation_services', 'tax_preparation_services'), ('tax_payments', 'tax_payments'), ('digital_goods', 'digital_goods'), ('atms', 'atms'), ('college', 'college'), ('schools', 'schools'), ('university', 'university'), ('professional_courses', 'professional_courses'), ('distance_learning', 'distance_learning'), ('day_care', 'day_care'), ('coaching', 'coaching'), ('elearning', 'elearning'), ('vocational_and_trade_schools', 'vocational_and_trade_schools'), ('sporting_clubs', 'sporting_clubs'), ('dance_halls_studios_and_schools', 'dance_halls_studios_and_schools'), ('correspondence_schools', 'correspondence_schools'), ('pharmacy', 'pharmacy'), ('clinic', 'clinic'), ('hospital', 'hospital'), ('lab', 'lab'), ('dietician', 'dietician'), ('fitness', 'fitness'), ('health_coaching', 'health_coaching'), ('health_products', 'health_products'), ('drug_stores', 'drug_stores'), ('healthcare_marketplace', 'healthcare_marketplace'), ('osteopaths', 'osteopaths'), ('medical_equipment_and_supply_stores', 'medical_equipment_and_supply_stores'), ('podiatrists_and_chiropodists', 'podiatrists_and_chiropodists'), ('dentists_and_orthodontists', 'dentists_and_orthodontists'), ('hardware_stores', 'hardware_stores'), ('ophthalmologists', 'ophthalmologists'), ('orthopedic_goods_stores', 'orthopedic_goods_stores'), ('testing_laboratories', 'testing_laboratories'), ('doctors', 'doctors'), ('health_practitioners_medical_services', 'health_practitioners_medical_services'), ('testing_laboratories', 'testing_laboratories'), ('ecommerce_marketplace', 'ecommerce_marketplace'), ('agriculture', 'agriculture'), ('books', 'books'), ('electronics_and_furniture', 'electronics_and_furniture'), ('coupons', 'coupons'), ('rental', 'rental'), ('fashion_and_lifestyle', 'fashion_and_lifestyle'), ('gifting', 'gifting'), ('grocery', 'grocery'), ('baby_products', 'baby_products'), ('office_supplies', 'office_supplies'), ('wholesale', 'wholesale'), ('religious_products', 'religious_products'), ('pet_products', 'pet_products'), ('sports_products', 'sports_products'), ('arts_and_collectibles', 'arts_and_collectibles'), ('sexual_wellness_products', 'sexual_wellness_products'), ('drop_shipping', 'drop_shipping'), ('crypto_machinery', 'crypto_machinery'), ('tobacco', 'tobacco'), ('weapons_and_ammunitions', 'weapons_and_ammunitions'), ('stamps_and_coins_stores', 'stamps_and_coins_stores'), ('office_equipment', 'office_equipment'), ('automobile_parts_and_equipements', 'automobile_parts_and_equipements'), ('garden_supply_stores', 'garden_supply_stores'), ('household_appliance_stores', 'household_appliance_stores'), ('non_durable_goods', 'non_durable_goods'), ('pawn_shops', 'pawn_shops'), ('electrical_parts_and_equipment', 'electrical_parts_and_equipment'), ('wig_and_toupee_shops', 'wig_and_toupee_shops'), ('gift_novelty_and_souvenir_shops', 'gift_novelty_and_souvenir_shops'), ('duty_free_stores', 'duty_free_stores'), ('office_and_commercial_furniture', 'office_and_commercial_furniture'), ('dry_goods', 'dry_goods'), ('books_and_publications', 'books_and_publications'), ('camera_and_photographic_stores', 'camera_and_photographic_stores'), ('record_shops', 'record_shops'), ('meat_supply_stores', 'meat_supply_stores'), ('leather_goods_and_luggage', 'leather_goods_and_luggage'), ('snowmobile_dealers', 'snowmobile_dealers'), ('men_and_boys_clothing_stores', 'men_and_boys_clothing_stores'), ('paint_supply_stores', 'paint_supply_stores'), ('automotive_parts', 'automotive_parts'), ('jewellery_and_watch_stores', 'jewellery_and_watch_stores'), ('auto_store_home_supply_stores', 'auto_store_home_supply_stores'), ('tent_stores', 'tent_stores'), ('shoe_stores_retail', 'shoe_stores_retail'), ('petroleum_and_petroleum_products', 'petroleum_and_petroleum_products'), ('department_stores', 'department_stores'), ('automotive_tire_stores', 'automotive_tire_stores'), ('sport_apparel_stores', 'sport_apparel_stores'), ('variety_stores', 'variety_stores'), ('chemicals_and_allied_products', 'chemicals_and_allied_products'), ('commercial_equipments', 'commercial_equipments'), ('fireplace_parts_and_accessories', 'fireplace_parts_and_accessories'), ('family_clothing_stores', 'family_clothing_stores'), ('fabric_and_sewing_stores', 'fabric_and_sewing_stores'), ('home_supply_warehouse', 'home_supply_warehouse'), ('art_supply_stores', 'art_supply_stores'), ('camper_recreational_and_utility_trailer_dealers', 'camper_recreational_and_utility_trailer_dealers'), ('clocks_and_silverware_stores', 'clocks_and_silverware_stores'), ('discount_stores', 'discount_stores'), ('school_supplies_and_stationery', 'school_supplies_and_stationery'), ('second_hand_stores', 'second_hand_stores'), ('watch_and_jewellery_repair_stores', 'watch_and_jewellery_repair_stores'), ('liquor_stores', 'liquor_stores'), ('boat_dealers', 'boat_dealers'), ('opticians_optical_goods_and_eyeglasse_stores', 'opticians_optical_goods_and_eyeglasse_stores'), ('wholesale_footwear_stores', 'wholesale_footwear_stores'), ('cosmetic_stores', 'cosmetic_stores'), ('home_furnishing_stores', 'home_furnishing_stores'), ('antique_stores', 'antique_stores'), ('plumbing_and_heating_equipment', 'plumbing_and_heating_equipment'), ('telecommunication_equipment_stores', 'telecommunication_equipment_stores'), ('women_clothing', 'women_clothing'), ('florists', 'florists'), ('computer_software_stores', 'computer_software_stores'), ('building_matrial_stores', 'building_matrial_stores'), ('candy_nut_confectionery_shops', 'candy_nut_confectionery_shops'), ('glass_and_wallpaper_stores', 'glass_and_wallpaper_stores'), ('commercial_photography_and_graphic_design_services', 'commercial_photography_and_graphic_design_services'), ('video_game_supply_stores', 'video_game_supply_stores'), ('fuel_dealers', 'fuel_dealers'), ('drapery_and_window_coverings_stores', 'drapery_and_window_coverings_stores'), ('hearing_aids_stores', 'hearing_aids_stores'), ('automotive_paint_shops', 'automotive_paint_shops'), ('durable_goods_stores', 'durable_goods_stores'), ('uniforms_and_commercial_clothing_stores', 'uniforms_and_commercial_clothing_stores'), ('fur_shops', 'fur_shops'), ('industrial_supplies', 'industrial_supplies'), ('bicycle_stores', 'bicycle_stores'), ('second_hand_stores', 'second_hand_stores'), ('motorcycle_shops_and_dealers', 'motorcycle_shops_and_dealers'), ('children_and_infants_wear_stores', 'children_and_infants_wear_stores'), ('women_accessory_stores', 'women_accessory_stores'), ('construction_materials', 'construction_materials'), ('books_periodicals_and_newspaper', 'books_periodicals_and_newspaper'), ('floor_covering_stores', 'floor_covering_stores'), ('crystal_and_glassware_stores', 'crystal_and_glassware_stores'), ('accessory_and_apparel_stores', 'accessory_and_apparel_stores'), ('hardware_equipment_and_supply_stores', 'hardware_equipment_and_supply_stores'), ('computers_peripheral_equipment_software', 'computers_peripheral_equipment_software'), ('automobile_and_truck_dealers', 'automobile_and_truck_dealers'), ('aircraft_and_farm_equipment_dealers', 'aircraft_and_farm_equipment_dealers'), ('antique_shops_sales_and_repairs', 'antique_shops_sales_and_repairs'), ('hearing_aids_stores', 'hearing_aids_stores'), ('music_stores', 'music_stores'), ('furniture_and_home_furnishing_store', 'furniture_and_home_furnishing_store'), ('repair_and_cleaning', 'repair_and_cleaning'), ('interior_design_and_architect', 'interior_design_and_architect'), ('movers_and_packers', 'movers_and_packers'), ('legal', 'legal'), ('event_planning', 'event_planning'), ('service_centre', 'service_centre'), ('consulting', 'consulting'), ('ad_and_marketing', 'ad_and_marketing'), ('services_classifieds', 'services_classifieds'), ('multi_level_marketing', 'multi_level_marketing'), ('construction_services', 'construction_services'), ('architectural_services', 'architectural_services'), ('car_washes', 'car_washes'), ('motor_home_rentals', 'motor_home_rentals'), ('stenographic_and_secretarial_support_services', 'stenographic_and_secretarial_support_services'), ('chiropractors', 'chiropractors'), ('automotive_service_shops', 'automotive_service_shops'), ('shoe_repair_shops', 'shoe_repair_shops'), ('telecommunication_service', 'telecommunication_service'), ('fines', 'fines'), ('security_agencies', 'security_agencies'), ('tailors', 'tailors'), ('type_setting_and_engraving_services', 'type_setting_and_engraving_services'), ('small_appliance_repair_shops', 'small_appliance_repair_shops'), ('photography_labs', 'photography_labs'), ('dry_cleaners', 'dry_cleaners'), ('massage_parlors', 'massage_parlors'), ('electronic_repair_shops', 'electronic_repair_shops'), ('cleaning_and_sanitation_services', 'cleaning_and_sanitation_services'), ('nursing_care_facilities', 'nursing_care_facilities'), ('direct_marketing', 'direct_marketing'), ('lottery', 'lottery'), ('veterinary_services', 'veterinary_services'), ('affliated_auto_rental', 'affliated_auto_rental'), ('alimony_and_child_support', 'alimony_and_child_support'), ('airport_flying_fields', 'airport_flying_fields'), ('golf_courses', 'golf_courses'), ('tire_retreading_and_repair_shops', 'tire_retreading_and_repair_shops'), ('television_cable_services', 'television_cable_services'), ('recreational_and_sporting_camps', 'recreational_and_sporting_camps'), ('barber_and_beauty_shops', 'barber_and_beauty_shops'), ('agricultural_cooperatives', 'agricultural_cooperatives'), ('carpentry_contractors', 'carpentry_contractors'), ('wrecking_and_salvaging_services', 'wrecking_and_salvaging_services'), ('automobile_towing_services', 'automobile_towing_services'), ('video_tape_rental_stores', 'video_tape_rental_stores'), ('miscellaneous_repair_shops', 'miscellaneous_repair_shops'), ('motor_homes_and_parts', 'motor_homes_and_parts'), ('horse_or_dog_racing', 'horse_or_dog_racing'), ('laundry_services', 'laundry_services'), ('electrical_contractors', 'electrical_contractors'), ('debt_marriage_personal_counseling_service', 'debt_marriage_personal_counseling_service'), ('air_conditioning_and_refrigeration_repair_shops', 'air_conditioning_and_refrigeration_repair_shops'), ('credit_reporting_agencies', 'credit_reporting_agencies'), ('heating_and_plumbing_contractors', 'heating_and_plumbing_contractors'), ('carpet_and_upholstery_cleaning_services', 'carpet_and_upholstery_cleaning_services'), ('swimming_pools', 'swimming_pools'), ('roofing_and_metal_work_contractors', 'roofing_and_metal_work_contractors'), ('internet_service_providers', 'internet_service_providers'), ('recreational_camps', 'recreational_camps'), ('masonry_contractors', 'masonry_contractors'), ('exterminating_and_disinfecting_services', 'exterminating_and_disinfecting_services'), ('ambulance_services', 'ambulance_services'), ('funeral_services_and_crematories', 'funeral_services_and_crematories'), ('metal_service_centres', 'metal_service_centres'), ('copying_and_blueprinting_services', 'copying_and_blueprinting_services'), ('fuel_dispensers', 'fuel_dispensers'), ('welding_repair', 'welding_repair'), ('mobile_home_dealers', 'mobile_home_dealers'), ('concrete_work_contractors', 'concrete_work_contractors'), ('boat_rentals', 'boat_rentals'), ('personal_shoppers_and_shopping_clubs', 'personal_shoppers_and_shopping_clubs'), ('door_to_door_sales', 'door_to_door_sales'), ('travel_related_direct_marketing', 'travel_related_direct_marketing'), ('lottery_and_betting', 'lottery_and_betting'), ('bands_orchestras_and_miscellaneous_entertainers', 'bands_orchestras_and_miscellaneous_entertainers'), ('furniture_repair_and_refinishing', 'furniture_repair_and_refinishing'), ('contractors', 'contractors'), ('direct_marketing_and_subscription_merchants', 'direct_marketing_and_subscription_merchants'), ('typewriter_stores_sales_service_and_rentals', 'typewriter_stores_sales_service_and_rentals'), ('recreation_services', 'recreation_services'), ('direct_marketing_insurance_services', 'direct_marketing_insurance_services'), ('business_services', 'business_services'), ('inbound_telemarketing_merchants', 'inbound_telemarketing_merchants'), ('public_warehousing', 'public_warehousing'), ('outbound_telemarketing_merchants', 'outbound_telemarketing_merchants'), ('clothing_rental_stores', 'clothing_rental_stores'), ('transportation_services', 'transportation_services'), ('electric_razor_stores', 'electric_razor_stores'), ('service_stations', 'service_stations'), ('photographic_studio', 'photographic_studio'), ('professional_services', 'professional_services'), ('developer', 'developer'), ('facility_management', 'facility_management'), ('rwa', 'rwa'), ('coworking', 'coworking'), ('realestate_classifieds', 'realestate_classifieds'), ('space_rental', 'space_rental'), ('charity', 'charity'), ('educational', 'educational'), ('religious', 'religious'), ('personal', 'personal'), ('matchmaking', 'matchmaking'), ('social_network', 'social_network'), ('messaging', 'messaging'), ('professional_network', 'professional_network'), ('neighbourhood_network', 'neighbourhood_network'), ('political_organizations', 'political_organizations'), ('automobile_associations_and_clubs', 'automobile_associations_and_clubs'), ('country_and_athletic_clubs', 'country_and_athletic_clubs'), ('associations_and_membership', 'associations_and_membership'), ('video_on_demand', 'video_on_demand'), ('music_streaming', 'music_streaming'), ('multiplex', 'multiplex'), ('content_and_publishing', 'content_and_publishing'), ('ticketing', 'ticketing'), ('news', 'news'), ('video_game_arcades', 'video_game_arcades'), ('video_tape_production_and_distribution', 'video_tape_production_and_distribution'), ('bowling_alleys', 'bowling_alleys'), ('billiard_and_pool_establishments', 'billiard_and_pool_establishments'), ('amusement_parks_and_circuses', 'amusement_parks_and_circuses'), ('ticket_agencies', 'ticket_agencies'), ('game_developer', 'game_developer'), ('esports', 'esports'), ('online_casino', 'online_casino'), ('fantasy_sports', 'fantasy_sports'), ('gaming_marketplace', 'gaming_marketplace'), ('saas', 'saas'), ('paas', 'paas'), ('iaas', 'iaas'), ('consulting_and_outsourcing', 'consulting_and_outsourcing'), ('web_development', 'web_development'), ('technical_support', 'technical_support'), ('data_processing', 'data_processing'), ('online_food_ordering', 'online_food_ordering'), ('restaurant', 'restaurant'), ('food_court', 'food_court'), ('catering', 'catering'), ('alcohol', 'alcohol'), ('restaurant_search_and_booking', 'restaurant_search_and_booking'), ('dairy_products', 'dairy_products'), ('bakeries', 'bakeries'), ('electricity', 'electricity'), ('gas', 'gas'), ('telecom', 'telecom'), ('water', 'water'), ('cable', 'cable'), ('broadband', 'broadband'), ('dth', 'dth'), ('internet_provider', 'internet_provider'), ('bill_and_recharge_aggregators', 'bill_and_recharge_aggregators'), ('central', 'central'), ('state', 'state'), ('intra_government_purchases', 'intra_government_purchases'), ('goverment_postal_services', 'goverment_postal_services'), ('freight', 'freight'), ('courier', 'courier'), ('warehousing', 'warehousing'), ('distribution', 'distribution'), ('end_to_end_logistics', 'end_to_end_logistics'), ('courier_services', 'courier_services'), ('aviation', 'aviation'), ('accommodation', 'accommodation'), ('ota', 'ota'), ('travel_agency', 'travel_agency'), ('tourist_attractions_and_exhibits', 'tourist_attractions_and_exhibits'), ('timeshares', 'timeshares'), ('aquariums_dolphinariums_and_seaquariums', 'aquariums_dolphinariums_and_seaquariums'), ('cab_hailing', 'cab_hailing'), ('bus', 'bus'), ('train_and_metro', 'train_and_metro'), ('automobile_rentals', 'automobile_rentals'), ('cruise_lines', 'cruise_lines'), ('parking_lots_and_garages', 'parking_lots_and_garages'), ('transportation', 'transportation'), ('bridge_and_road_tolls', 'bridge_and_road_tolls'), ('freight_transport', 'freight_transport'), ('truck_and_utility_trailer_rentals', 'truck_and_utility_trailer_rentals')], max_length=255, null=True)),
                ('pan', models.CharField(blank=True, max_length=255, null=True)),
                ('gstin', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_ifsc', models.CharField(max_length=255)),
                ('bank_account_holder_name', models.CharField(max_length=255)),
                ('business_pan', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('payment_gateway_configs', models.JSONField(blank=True, null=True)),
                ('payment_link_configs', models.JSONField(blank=True, null=True)),
                ('gateway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboardings', to='airpay.paymentgateway')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airpay.airseller')),
            ],
        ),
        migrations.CreateModel(
            name='RazorpayOnboardingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street1', models.TextField(blank=True, null=True)),
                ('street2', models.TextField()),
                ('type', models.CharField(choices=[('registered', 'Registered'), ('individual', 'Individual'), ('operations', 'Operations')], max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('razorpay_route_onboarding_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='airpay.razorpayrouteonboardingdetails')),
            ],
        ),
        migrations.AddField(
            model_name='airplan',
            name='features',
            field=models.ManyToManyField(related_name='features', to='airpay.airplanfeatures'),
        ),
        migrations.AddField(
            model_name='airplan',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airpay.paymentgateway'),
        ),
    ]
