# Generated by Django 4.2.10 on 2024-06-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
