# Generated by Django 6.0 on 2026-06-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airpay", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplan",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("3_month", "3 Month"),
                    ("9_month", "9 Month"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptions",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("3_month", "3 Month"),
                    ("9_month", "9 Month"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                max_length=255,
            ),
        ),
    ]
