# Generated by Django 6.0 on 2026-07-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpay', '0002_alter_airplan_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('3_month', '3 Month'), ('5_month', '5 Month'), ('9_month', '9 Month'), ('yearly', 'Yearly')], default='monthly', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('3_month', '3 Month'), ('5_month', '5 Month'), ('9_month', '9 Month'), ('yearly', 'Yearly')], default='monthly', max_length=255),
        ),
    ]
