# Generated by Django 4.2.10 on 2024-06-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpay', '0002_subscriptions_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='business_pan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='razorpay_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
