# Generated by Django 6.0 on 2026-07-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # 0002_alter_airplan_billing_cycle_and_more was removed when migrations
        # were squashed into 0001_initial (3a320fc). This migration is the
        # CN-94 5_month billing_cycle addition and chains from initial.
        ('airpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('3_month', '3 Month'), ('5_month', '5 Month'), ('9_month', '9 Month'), ('yearly', 'Yearly')], default='monthly', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('3_month', '3 Month'), ('5_month', '5 Month'), ('9_month', '9 Month'), ('yearly', 'Yearly')], default='monthly', max_length=255),
        ),
    ]
