# Generated by Django 4.2.10 on 2024-07-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpay', '0003_alter_razorpayrouteonboardingdetails_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airseller',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
