# Generated by Django 6.0 on 2026-07-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpay', '0003_alter_airplan_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplan',
            name='gateway_plan_id',
            field=models.CharField(blank=True, help_text="The REAL gateway-side plan id (e.g. Razorpay 'plan_XXXXXXXXXXXX'), distinct from plan_id (our internal natural key). Razorpay subscription.create requires an actual Razorpay Plan object id — plan_id was previously passed directly and would fail against the live API since it never matched a real Razorpay plan. Lazily created + cached here on first use (see razorpay_plan_sync.get_or_create_gateway_plan).", max_length=255, null=True),
        ),
    ]
