# Generated by Django 4.2.10 on 2024-07-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpay', '0005_airpaytransferlogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airpaytransferlogs',
            name='status',
        ),
        migrations.AddField(
            model_name='airpaytransferlogs',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='airpaytransferlogs',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airpaytransferlogs',
            name='settlement_status',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='airpaytransferlogs',
            name='transfer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airpaytransferlogs',
            name='transfer_status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
