# Generated by Django 4.2.10 on 2024-07-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpay', '0007_airplan_created_at_airplan_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpayonboardingaddress',
            name='street2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
