# Generated by Django 4.2.10 on 2024-07-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpay', '0008_alter_razorpayonboardingaddress_street2'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpayrouteonboardingdetails',
            name='route_configs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
