# Generated by Django 4.2.10 on 2024-07-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpay', '0009_razorpayrouteonboardingdetails_route_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpayrouteonboardingdetails',
            name='notified_for',
            field=models.BooleanField(default=False),
        ),
    ]
