# Generated by Django 4.2.10 on 2024-07-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpay', '0010_razorpayrouteonboardingdetails_notified_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='notified_for',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
