# Generated by Django 4.2.10 on 2024-07-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpay', '0011_alter_razorpayrouteonboardingdetails_notified_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airseller',
            name='needs_route',
            field=models.BooleanField(default=True),
        ),
    ]
