# Generated by Django 4.2.10 on 2024-08-26 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airpay', '0013_alter_razorpayrouteonboardingdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboardings', to='airpay.paymentgateway'),
        ),
    ]
