# Generated by Django 4.2.10 on 2025-02-18 21:12

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('airpay', '0015_alter_razorpayrouteonboardingdetails_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='bank_account_holder_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='bank_account_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='bank_ifsc',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='bank_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='business_pan',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='gstin',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='pan',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
