# Generated by Django 4.2.10 on 2026-01-27 18:04

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('airpay', '0016_alter_razorpayrouteonboardingdetails_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airpaytransferlogs',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='airplan',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='airplanfeatures',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='airseller',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='razorpayonboardingaddress',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='razorpayrouteonboardingdetails',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ['-create_date']},
        ),
        migrations.RenameField(
            model_name='airpaytransferlogs',
            old_name='updated_at',
            new_name='update_date',
        ),
        migrations.RenameField(
            model_name='airplan',
            old_name='updated_at',
            new_name='update_date',
        ),
        migrations.RenameField(
            model_name='airplanfeatures',
            old_name='updated_at',
            new_name='update_date',
        ),
        migrations.RenameField(
            model_name='airseller',
            old_name='updated_at',
            new_name='update_date',
        ),
        migrations.RenameField(
            model_name='paymentgateway',
            old_name='updated_at',
            new_name='update_date',
        ),
        migrations.RenameField(
            model_name='razorpayonboardingaddress',
            old_name='updated_at',
            new_name='update_date',
        ),
        migrations.RenameField(
            model_name='razorpayrouteonboardingdetails',
            old_name='updated_at',
            new_name='update_date',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='updated_at',
            new_name='update_date',
        ),
        migrations.RemoveField(
            model_name='airpaytransferlogs',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='airplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='airplanfeatures',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='airseller',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='razorpayonboardingaddress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='razorpayrouteonboardingdetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='created_at',
        ),
        migrations.AddField(
            model_name='airpaytransferlogs',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='airpaytransferlogs',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='airplan',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='airplan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='airplanfeatures',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='airplanfeatures',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='airseller',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='airseller',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='razorpayonboardingaddress',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='razorpayonboardingaddress',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='razorpayrouteonboardingdetails',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='razorpayrouteonboardingdetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='airpaytransferlogs',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='airplan',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='airplanfeatures',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='airseller',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='razorpayonboardingaddress',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='razorpayrouteonboardingdetails',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
