# Generated by Django 4.2.10 on 2026-01-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpay', '0017_alter_airpaytransferlogs_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=255),
        ),
    ]
