# Generated by Django 4.2.10 on 2026-01-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpay', '0018_subscriptions_billing_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=255),
        ),
    ]
