# Generated by Django 6.0 on 2026-04-08 17:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airpay", "0019_airplan_billing_cycle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airpaytransferlogs",
            options={},
        ),
        migrations.AlterModelOptions(
            name="airplan",
            options={},
        ),
        migrations.AlterModelOptions(
            name="airplanfeatures",
            options={},
        ),
        migrations.AlterModelOptions(
            name="airseller",
            options={},
        ),
        migrations.AlterModelOptions(
            name="paymentgateway",
            options={},
        ),
        migrations.AlterModelOptions(
            name="razorpayonboardingaddress",
            options={},
        ),
        migrations.AlterModelOptions(
            name="razorpayrouteonboardingdetails",
            options={},
        ),
        migrations.AlterModelOptions(
            name="subscriptions",
            options={},
        ),
        migrations.RemoveField(
            model_name="airpaytransferlogs",
            name="create_date",
        ),
        migrations.RemoveField(
            model_name="airpaytransferlogs",
            name="update_date",
        ),
        migrations.RemoveField(
            model_name="airplan",
            name="create_date",
        ),
        migrations.RemoveField(
            model_name="airplan",
            name="update_date",
        ),
        migrations.RemoveField(
            model_name="airplanfeatures",
            name="create_date",
        ),
        migrations.RemoveField(
            model_name="airplanfeatures",
            name="update_date",
        ),
        migrations.RemoveField(
            model_name="airseller",
            name="create_date",
        ),
        migrations.RemoveField(
            model_name="airseller",
            name="update_date",
        ),
        migrations.RemoveField(
            model_name="paymentgateway",
            name="create_date",
        ),
        migrations.RemoveField(
            model_name="paymentgateway",
            name="update_date",
        ),
        migrations.RemoveField(
            model_name="razorpayonboardingaddress",
            name="create_date",
        ),
        migrations.RemoveField(
            model_name="razorpayonboardingaddress",
            name="update_date",
        ),
        migrations.RemoveField(
            model_name="razorpayrouteonboardingdetails",
            name="create_date",
        ),
        migrations.RemoveField(
            model_name="razorpayrouteonboardingdetails",
            name="update_date",
        ),
        migrations.RemoveField(
            model_name="subscriptions",
            name="create_date",
        ),
        migrations.RemoveField(
            model_name="subscriptions",
            name="update_date",
        ),
        migrations.AddField(
            model_name="airpaytransferlogs",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="create_date",
                default=django.utils.timezone.now,
                help_text="Timestamp when the record was created",
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="airpaytransferlogs",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_column="update_date",
                help_text="Timestamp when the record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AddField(
            model_name="airplan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="create_date",
                default=django.utils.timezone.now,
                help_text="Timestamp when the record was created",
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="airplan",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_column="update_date",
                help_text="Timestamp when the record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AddField(
            model_name="airplanfeatures",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="create_date",
                default=django.utils.timezone.now,
                help_text="Timestamp when the record was created",
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="airplanfeatures",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_column="update_date",
                help_text="Timestamp when the record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AddField(
            model_name="airseller",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="create_date",
                default=django.utils.timezone.now,
                help_text="Timestamp when the record was created",
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="airseller",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_column="update_date",
                help_text="Timestamp when the record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="create_date",
                default=django.utils.timezone.now,
                help_text="Timestamp when the record was created",
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_column="update_date",
                help_text="Timestamp when the record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AddField(
            model_name="razorpayonboardingaddress",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="create_date",
                default=django.utils.timezone.now,
                help_text="Timestamp when the record was created",
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="razorpayonboardingaddress",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_column="update_date",
                help_text="Timestamp when the record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AddField(
            model_name="razorpayrouteonboardingdetails",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="create_date",
                default=django.utils.timezone.now,
                help_text="Timestamp when the record was created",
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="razorpayrouteonboardingdetails",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_column="update_date",
                help_text="Timestamp when the record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AddField(
            model_name="subscriptions",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="create_date",
                default=django.utils.timezone.now,
                help_text="Timestamp when the record was created",
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscriptions",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_column="update_date",
                help_text="Timestamp when the record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="airpaytransferlogs",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="airplan",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="airplanfeatures",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="airseller",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="paymentgateway",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="razorpayonboardingaddress",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="razorpayrouteonboardingdetails",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptions",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
