# Generated by Django 6.0 on 2026-04-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airpay", "0020_alter_airpaytransferlogs_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplan",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="Generic JSON metadata for plan-specific settings",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="airplan",
            name="tier_level",
            field=models.CharField(
                blank=True,
                help_text="Generic tier/level identifier (e.g., companion, guardian, medical, alumni)",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="airplanfeatures",
            name="config_value",
            field=models.JSONField(
                blank=True,
                help_text="Generic JSON configuration for feature-specific settings",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="airplanfeatures",
            name="feature_key",
            field=models.CharField(
                blank=True,
                help_text="Unique feature identifier for programmatic access",
                max_length=255,
                null=True,
            ),
        ),
    ]
