# Generated by Django 6.0 on 2026-04-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airpay", "0022_seed_tier_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplan",
            name="is_addon",
            field=models.BooleanField(default=False),
        ),
    ]
